#!/usr/bin/python
# -*- coding: UTF-8 -*-

import smtplib      # 导入 smtplib 邮件处理库
from email.mime.text import MIMEText
from email.utils import formataddr
import email
import os

mail_server = "smtp.sd.chinamobile.com"        # 发件人的 SMTP 服务器
port = "465"  # 服务端口

sender = "sunxiaohui@sd.chinamobile.com"     # 发件人邮箱帐号
sender_passw = "dJwcbao37681"         # 发件人邮箱密码(第3方登录授权密码)
receiver = "18863189005@139.com"      # 收件人邮箱帐号

#msg = MIMEText("hello world!", "plain", "utf-8")      # 邮件内容（正文）  需要发送HTML文件时，plain 改为 html 即可!


#把文本内容压缩到附件中
'''
basename = os.path.basename("text.txt")
msg.add_header('Content-Disposition','attachment', filename = "text.txt")#修改邮件头
'''
#main_msg = email.MIMEMultipart()

msg = MIMEText(open('text.txt', 'rb').read(), 'base64', 'utf-8')



msg["Content-Type"] = 'application/octet-stream'
# 这里的filename可以任意写，写什么名字，邮件中显示什么名字
msg["Content-Disposition"] = 'attachment; filename="text.txt"'

msg['From'] = formataddr(["sxh", sender])      # 发件人信息
msg['To'] = formataddr(["xiaohui", receiver])      # 收件人信息
msg['Subject'] = "测试邮件-sxh"       # 邮件的主题

#发文本的时候可以添加
msg2 =MIMEText("hello world!", "plain", "utf-8")




def sendMail(mail_server, port, sender,sender_passw, receiver):
    try:
        print("this is 4 ...")
        mail = smtplib.SMTP_SSL(mail_server, port)  # 使用SMTP()方法指向服务器（使用QQ邮箱服务器时，需改用 SMTP_SSL()方法）
        print("this is 3 ...")
        mail.login(sender, sender_passw)    # 请求服务器，登录帐号
        print("this is 2 ...")
        mail.sendmail(sender, [receiver], msg.as_string() )   # 发送邮件(给receiver传入列表时，表示群发)
        print("this is 1 ...")
        mail.quit()     # 断开连接
        print("邮件发送成功！")
    except:
        mail.quit()
        print("邮件发送失败！")


sendMail(mail_server, port, sender,sender_passw, receiver)
